### ISSUE TITLE
Don't use "loadConfigFile" from rollup

### ISSUE THREAD

**Issue by lukas-schardt** [webtides/luna-js#98]
The 'loadConfigFile' functionality is not inisde the exports map from rollup.js. This means it shows a warning in Node v16 and will break in Node v17.

We need to find an alternative way to load the `rollup.config.js` inside luna.

**Comment by eddyloewen** [comment]
@lukas-schardt this should be fixed with rollup#v2.70.1 no?

See: https://github.com/rollup/rollup/pull/4436
